version: '3.8'

services:
  luxveris_web:
    build:
      context: .            # Project root so Docker sees package.json etc.
      dockerfile: backend/Dockerfile
    container_name: luxveris_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html          # Backend code live-mount
      - ./backend/uploads:/var/www/html/uploads
    depends_on:
      - luxveris_db
    networks:
      - luxveris_network

  luxveris_db:
    image: mariadb:10.11
    container_name: luxveris_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: luxveris_db
      MYSQL_USER: luxveris
      MYSQL_PASSWORD: "12?34?56?Aa"
    ports:
      - "3307:3306"
    volumes:
      - luxveris_data:/var/lib/mysql     # Persistent DB volume
    networks:
      - luxveris_network

volumes:
  luxveris_data:

networks:
  luxveris_network:
